CREATE DATABASE 'localhost:C:\dev\cppbuilder2010\proyectos\pdv\database\EMPLOYEE.FDB'
USER 'SYSDBA' PASSWORD '**********'
PAGE_SIZE 4096
DEFAULT CHARACTER SET NONE;

/* Tables */
CREATE TABLE COUNTRY (
  COUNTRY   COUNTRYNAME NOT NULL,
  CURRENCY  VARCHAR(10) NOT NULL
) ;

CREATE TABLE CUSTOMER (
  CUST_NO         CUSTNO NOT NULL,
  CUSTOMER        VARCHAR(25) NOT NULL,
  CONTACT_FIRST   "FIRSTNAME",
  CONTACT_LAST    "LASTNAME",
  PHONE_NO        PHONENUMBER,
  ADDRESS_LINE1   ADDRESSLINE,
  ADDRESS_LINE2   ADDRESSLINE,
  CITY            VARCHAR(25),
  STATE_PROVINCE  VARCHAR(15),
  COUNTRY         COUNTRYNAME,
  POSTAL_CODE     VARCHAR(12),
  ON_HOLD         CHAR DEFAULT NULL
) ;
COMMIT;

/* Indexes */
CREATE INDEX CUSTNAMEX
  ON CUSTOMER
  (CUSTOMER);
CREATE INDEX CUSTREGION
  ON CUSTOMER
  (COUNTRY, CITY);

/* Constraints */
ALTER TABLE COUNTRY
  ADD PRIMARY KEY (COUNTRY);

ALTER TABLE CUSTOMER
  ADD PRIMARY KEY (CUST_NO);

ALTER TABLE CUSTOMER
  ADD CHECK (on_hold IS NULL OR on_hold = '*');

COMMIT;
/* Foreign Keys */
ALTER TABLE CUSTOMER
  ADD FOREIGN KEY (COUNTRY)
    REFERENCES COUNTRY(COUNTRY);

/* Triggers */
SET TERM ^ ;
CREATE TRIGGER SET_CUST_NO FOR CUSTOMER
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (new.cust_no is null) then
    new.cust_no = gen_id(cust_no_gen, 1);
END^
SET TERM ; ^

/* Grants */
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES
  ON TABLE COUNTRY
TO PUBLIC WITH GRANT OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES
  ON TABLE CUSTOMER
TO PUBLIC WITH GRANT OPTION;

